# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='story_document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=50)),
                ('upvotes', models.IntegerField(default=0)),
                ('sub_id', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=50)),
                ('sub_reddit', models.CharField(max_length=50)),
                ('archived', models.BooleanField(default=True)),
                ('over_18', models.BooleanField(default=False)),
                ('file_path', models.CharField(max_length=100)),
            ],
        ),
    ]
