# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiverse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story_document',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='story_document',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='story_document',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='story_document',
            name='over_18',
        ),
        migrations.RemoveField(
            model_name='story_document',
            name='sub_id',
        ),
        migrations.RemoveField(
            model_name='story_document',
            name='sub_reddit',
        ),
        migrations.RemoveField(
            model_name='story_document',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='story_document',
            name='upvotes',
        ),
    ]
