# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiverse', '0002_auto_20160427_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sims',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=30)),
                ('upvotes', models.PositiveIntegerField()),
                ('likes', models.PositiveIntegerField()),
                ('domain', models.CharField(max_length=100)),
                ('domainID', models.CharField(max_length=100)),
                ('nsfw', models.BooleanField()),
                ('archived', models.BooleanField()),
                ('tags', models.CharField(blank=True, max_length=100)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='story_document',
        ),
    ]
